### ISSUE TITLE
Compiler caused error: Missing mandatory field Value.value

### ISSUE THREAD

**Issue by joneff** [sass/dart-sass-embedded#74]
First of all, bravo, for all the hard work! I am working with especially large sass project, so sass-embedded brings significant speed increase over dart-sass.

I am using a sort of hack to get all sass variables, along with their type and value like so:

```scss
// all.scss
$var1: 1;
$var2: 2px;

@import "PATH_TO_NODE_MODULES/bootstrap/scss/bootstrap.scss";
```

```scss
// variables.scss
@use "sass:meta";
@use "all.scss";

$_vars: meta.module-variables("all");

body {
    @each $key, $val in $_vars {
        var: resolve-var( unquote($key), meta.type-of( $val ), $val );
    }
}
```

Then I am compiling the file by passing a custom function like so:

```js
const fs = require('fs');
const path = require('path');
const sassEmbedded = require('sass-embedded');

const cwd = process.cwd();

let variablesJson = path.resolve( cwd, `dist/variables.json` );
let variablesScss = path.resolve( cwd, `dist/variables.scss` );
let content = {};

sassEmbedded.compile(variablesScss, {
    functions: {
        'resolve-var($key, $type, $value)': (args) => {
            const _key = args[0].toString();
            const _type = args[1].toString();
            const _val = args[2].toString();

            content[_key] = {
                type: _type,
                value: _val
            };

            return sassEmbedded.sassNull;
        }
    },
    logger: sassEmbedded.Logger.silent
});

fs.writeFileSync( variablesJson, JSON.stringify( content, null, 4 ) );
```

The above works with sass.

With sass embedded it throws an error:  `Compiler caused error: Missing mandatory field Value.value.` If I console log right after variable assignment, the last successful parsed variable is `$input-height-border`. So the one that's failing should be https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L839. It's worth noting that I've tried with calc and it also fails. other functions pass. 

On a side note, if I comment out bootstrap.scss and console.log(_val), I get different return types:
* dartSass yields `1` and `2px`
* dartEmbedded yields `1no unit` and `2px`
