### ISSUE TITLE
Build native executables for macos-arm64

### ISSUE THREAD

**Issue by larsgrefer** [sass/dart-sass-embedded#90]
I've just done some performance comparisons on my M1 Mac I wanted to share with you:

It seems that the `macos-x64` variant of `dart-sass-embedded` running on Rosetta 2 is faster than the 'native' `macos-arm64` variant.
The `macos-x64` variant is also much smaller (~3MB vs ~16MB)

### Test 1
Executing this shell command:

```shell
time dart-sass-embedded --version
```

macos-x64 on Rosetta: ~40-50 ms
macos-arm64 native: ~70-80 ms

### Test 2

Compiling the following SCSS 100 times:

```scss
.foo { .bar { color : #ffffff; @warn 'haha';}}
```

macos-x64 on Rosetta: ~90 ms
macos-arm64 native: ~110-130 ms

Does somebody have an explanation for this?
Or does someone notices similar problems?

With the current status, I'm actually considering not to bundle the native arm variant into https://github.com/larsgrefer/dart-sass-java anymore as it seems superfluous to carry the extra 16 MB for worse performance.

**Comment by ntkme** [comment]
https://dart.dev/tools/dart-compile#types-of-output

The macOS arm64 is a script snapshot because Dart still don’t support cross compile. To provide native exe we will need a macOS arm64 GitHub Action runner.

@nex3 An option to consider if team is open to the idea would be https://www.macstadium.com/opensource. They provide free macOS arm64 GitHub Action runners for open source, which other projects like JRuby is currently using.

**Comment by nex3** [comment]
> An option to consider if team is open to the idea would be https://www.macstadium.com/opensource. They provide free macOS arm64 GitHub Action runners for open source, which other projects like JRuby is currently using.

This definitely sounds like the best way forward.

**Comment by larsgrefer** [comment]
@ntkme Thanks for the clarification. I assume the same applies to the `windows-ia32` and `linux-ia32` builds which are also ~16MB in size?

It would be great to have a "real" native `macos-arm64` variant, because, with the status quo, x64 on Rosetta seems so to be the better option.

**Comment by ntkme** [comment]
> I assume the same applies to the `windows-ia32` and `linux-ia32` builds which are also ~16MB in size?

Yes.

**Comment by Goodwine** [comment]
Would something like running this instead work for macos-arm64?  
```yaml
steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with: {architecture: arm64}
      - run: arch -arm64 dart pub get
      - name: Deploy
        run: arch -arm64 dart run grinder pkg-github-macos-arm64
```

I guess.. it won't work?
